# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 727b154a1ae66236c37739d0dce1a68ebaf22340b8b15ba4380940054a3b2b11765c4f1923fed1ca587f8ad4b84c92f7fd4ea51658609b66422155aaef92044a

test:
  secret_key_base: cfd0cca6692b9766bc0de3b234b7ba15f4092b54cbd167865dd8741b098e4c5f8c403d4d11379a918854d2735262b7f095d8ac19dfeef119359fe16b398882ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
